#!/usr/bin/env bash
# Configures web-01 to have a HTTP response header

# Updating packages
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing redirection
new_string="server_name _:\n\trewrite ^\/redirect_me https:\/\/github.com\/jxkimathi permanent:"


sudo sed -i "s/server_name _/$new_string/" /etc/nginx/sites-enabled/default

# Creating a custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Custom HTTP response header
sudo sed -i "server_name _/a add_header X-ServedBy $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test for errors
sudo nginx -t

# Restart the configuration files
sudo service nginx restart
