#!/usr/bin/env bash
# Sets up the HAProxy

# Install haproxy
sudo apt-get -y update
sudo apt-get install -y haproxy

# Edit config file
server_config=\
"
frontend http_front
    bind *:80
    mode http
    default_backend http_back
backend http_back
    balance roundrobin
    server 254938-web-01 52.204.145.159 check
    server 254938-web-02 54.237.81.200 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable haproxy to be started with init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the config file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart nginx service
sudo service haproxy restart
