#!/usr/bin/env bash
# Displays numbers 1-100
#   prints Fizz every multiple of 3
#   prints Buzz every multiple of 5
#   prints FizzBuzz every multiple of 3 and 5

for num in {1..100}
do
    if (( num % 3 == 0 && num % 5 == 0 ))
    then
        echo "FizzBuzz"
    elif (( num % 3 == 0 ))
    then
        echo "Fizz"
    elif (( num % 5 == 0 ))
    then
        echo "Buzz"
    else
        echo "$num"
    fi
done